language: node_js
node_js:
- 12.18.3

brances:
  only:
  - develop

cache:
  directories: 
    – node_modules

before_install:
- cd server
- openssl aes-256-cbc -K $encrypted_3b9f0b9d36d1_key -iv $encrypted_3b9f0b9d36d1_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar

before_deploy:
  - mkdir -p before-deploy
  - cp ./../scripts/*.sh before-deploy/
  - cp ./../appspec.yml before-deploy/
  - cd ../ zip -r Praise-Server *
  - mv Praise-Server.zip before-deploy/Praise-Server.zip


deploy:
  - provider: s3
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"

    bucket: aws-gyun-s3
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: before-deploy  # 위에 before_deploy 에서 mkdir 한 디렉토리 이름과 같아야 함
    wait-until-deployed: true
    on:
      branch: develop

notification:
  email:
    recipients:
    - wjdrbs966@naver.com
